### ISSUE TITLE
Combining use_Gaussian and Boson_from_table doesn't work

### ISSUE THREAD

**Issue by nominhanggai** [mcygorek/ACE#1]
Hi Moritz,

I was trying to set `use_Gaussian=true` and running the following input file. ACE refused to run and told me `"Spectral density: Please specify either 'Boson_J_from_file' or 'Boson_J_type'!"`. But I did provide the bath information by `Boson_from_table`.

The param file:

> te 0.01
> dt 1e-4
> 
> threshold 1e-4
> 
> add_Hamiltonian    {1941.30331441*|0><0|_3 + 1940.54152688*|1><1|_3 + 819.22815132*|2><2|_3 + 300*(|1><0|_3+|0><1|_3) + 50*(|1><2|_3+|2><1|_3)}
> Boson_N_modes 2
> Boson_SysOp {|0><0|_3 + 0.4106715589673543*|1><1|_3 - 0.5558270843261847 *|2><2|_3}
> Boson_from_table bath.tab
> Boson_temperature 300
> 
> initial {|0><0|_3}
> 
> add_Output {|0><0|_3}

The `bath.tab` file used in the param file:

> 149.61595332328773	-16.19912480931177
> 1384.3902121938977	-828.2229687682933

Is this by design or did I do something wrong? Thanks!

**Comment by mcygorek** [comment]
Hi,

thanks for your interest in ACE. 

First, let me comment on how to use ACE with use_Gaussian=false for your example:

1. First of all, the parameter is 'Boson_E_g_from_table', not 'Boson_from_table'.
2. You would want to set dict_zero=1e-20  (something small but greater zero). This will speed up calculations dramatically for your case making use of the fact that the coupling operator is diagonal. This is related to the reduction of outer indices briefly discussed for the superradiance example in the SM of the ACE paper.
3. You absolutely need to set Boson_M in your case. This describes the Hilbert space dimension per mode and has a default value of Boson_M=2. For a strongly coupled spin-boson model, it's easy to emit more phonons and you're already using a high temperature of 300K. I checked that, in your case, convergence is reached for Boson_M=4.

The following works for me:


```
te 0.01
dt 1e-4

threshold 1e-8
dict_zero 1e-20

add_Hamiltonian {1941.30331441*|0><0|_3 + 1940.54152688*|1><1|_3 + 819.22815132*|2><2|_3 + 300*(|1><0|_3+|0><1|_3) + 50*(|1><2|_3+|2><1|_3)}

Boson_N_modes 2
Boson_M       5
Boson_SysOp {|0><0|_3 + 0.4106715589673543*|1><1|_3 - 0.5558270843261847 *|2><2|_3}
Boson_E_g_from_table bath.tab
Boson_temperature 300

initial           {|0><0|_3}
add_Output        {|0><0|_3}
```



Regarding the combination with use_Gaussian=true: The latter uses my implementation of the algorithm by Jorgensen and Pollock [Phys. Rev. Lett. 123, 240602 (2019)], which has also been implemented in OQuPy. For Gaussian PTs, calculations start from the spectral density and the description in terms of discrete modes is less natural. 
As shown in the SM of the ACE paper, for discrete modes, ACE is faster than the Gaussian PT calculation because of the different scaling w.r.t. memory time and number of modes. 
Instead of using the table you can also calculate a spectral density that emulates discrete modes by replacing the delta-function in the definition of J(omega) by something with a finite width. The simplest is using boxes keeping in mind that the code linearly interpolates between sample points and uses the first/last value outside of the domain. Below is a version that works for me:


```
te 0.005
dt 1e-4

threshold 1e-8
dict_zero 1e-20

add_Hamiltonian {1941.30331441*|0><0|_3 + 1940.54152688*|1><1|_3 + 819.22815132*|2><2|_3 + 300*(|1><0|_3+|0><1|_3) + 50*(|1><2|_3+|2><1|_3)}


use_Gaussian  true
Boson_SysOp {|0><0|_3 + 0.4106715589673543*|1><1|_3 - 0.5558270843261847 *|2><2|_3}
Boson_J_from_file bath.J
Boson_E_min   140   
Boson_E_max   1400  
Boson_temperature 300

initial           {|0><0|_3}
add_Output        {|0><0|_3}
```

with file bath.J:
```
#149.61595332328773 -16.19912480931177   
# \omega=E/hbar-> 227.30664758497906588241  
# and use box width dw=1 ->    second column |g|^2 /dw 
226.806  0
226.80664758497906588241  262.411644587660088764500
227.80664758497906588241  262.411644587660088764500
227.807  0


#1384.3902121938977 -828.2229687682933
#divide energy by hbar-> 2103.25898471064025120872  
2102.758  0
2102.75898471064025120872    685953.28599536533903130339
2103.75898471064025120872    685953.28599536533903130339
2103.759  0
```

Note that I only calculate up to half the 'te' of the above example because it takes so much longer.

I currently see no clear rationale for implementing and maintaining additionally combining the two flags and there is a massive amount of more useful features that still require work.

Finally, if you compare your results with other codes, you might want to set Boson_subtract_polaron_shift=true to subtract the polaron shift.

If you have more questions or are interested in a collaboration, feel free to send an email to my Heriot-Watt address.

Best,
Moritz
